#!/usr/bin/env ruby
# frozen_string_literal: true

require "ys1"
require "rake"

YS1::Cmd.usage(__FILE__, '<"CSV glob">') if ARGV.empty?

FileList[ARGV].map do |file|
  YS1::Csv.generate_json_file(file, format = :array)
end
