name: merge-push

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  merge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'workshop'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge workshop into main
        run: |
          git fetch origin workshop
          git merge origin/workshop --no-ff -m "Auto merge workshop into main"

      - name: Push changes
        run: |
          git push origin main
